"""add llm tracking to scraper runs

Revision ID: 372e2c7d8198
Revises: 881c8ee7a06f
Create Date: 2026-04-21 01:26:41.676656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372e2c7d8198'
down_revision = '881c8ee7a06f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraper_runs', sa.Column('total_tokens', sa.Integer(), server_default='0', nullable=False))
    op.add_column('scraper_runs', sa.Column('total_cost', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraper_runs', 'total_cost')
    op.drop_column('scraper_runs', 'total_tokens')
    # ### end Alembic commands ###
