"""add_subscription_fields

Revision ID: 3cef00bad943
Revises: 025_user_profile_fields
Create Date: 2026-04-30 01:35:51.506481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cef00bad943'
down_revision = '025_user_profile_fields'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('users', sa.Column('subscription_plan', sa.String(length=50), server_default='free', nullable=False))
    op.add_column('users', sa.Column('subscription_expiry', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_payment_id', sa.String(length=100), nullable=True))
    
    # Add is_featured to subscription_plans
    op.add_column('subscription_plans', sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_payment_id')
    op.drop_column('users', 'subscription_expiry')
    op.drop_column('users', 'subscription_plan')
    op.create_unique_constraint('company_profiles_domain_key', 'company_profiles', ['domain'])
    # ### end Alembic commands ###
