"""Add company_briefings table

Revision ID: 589bbd66287d
Revises: e7c5d2bb98f4
Create Date: 2026-04-04 20:57:49.905865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '589bbd66287d'
down_revision = 'e7c5d2bb98f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_briefings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('role_title', sa.String(), nullable=False),
    sa.Column('briefing_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_briefings_company_name'), 'company_briefings', ['company_name'], unique=False)
    op.create_index(op.f('ix_company_briefings_id'), 'company_briefings', ['id'], unique=False)
    op.create_index(op.f('ix_company_briefings_role_title'), 'company_briefings', ['role_title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_briefings_role_title'), table_name='company_briefings')
    op.drop_index(op.f('ix_company_briefings_id'), table_name='company_briefings')
    op.drop_index(op.f('ix_company_briefings_company_name'), table_name='company_briefings')
    op.drop_table('company_briefings')
    # ### end Alembic commands ###
