"""Add TokenUsage table

Revision ID: 881c8ee7a06f
Revises: 022_merge_heads_019_021
Create Date: 2026-04-16 00:22:39.992944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '881c8ee7a06f'
down_revision = '022_merge_heads_019_021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('feature', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_usage_email'), 'token_usage', ['email'], unique=False)
    op.create_index(op.f('ix_token_usage_id'), 'token_usage', ['id'], unique=False)
    op.create_index(op.f('ix_token_usage_model'), 'token_usage', ['model'], unique=False)
    op.create_index(op.f('ix_token_usage_user_id'), 'token_usage', ['user_id'], unique=False)
    op.drop_index('ix_token_usage_logs_id', table_name='token_usage_logs')
    op.drop_index('ix_token_usage_logs_occurred_at', table_name='token_usage_logs')
    op.drop_index('ix_token_usage_logs_user_id', table_name='token_usage_logs')
    op.drop_table('token_usage_logs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_usage_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('usage_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('prompt_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completion_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='token_usage_logs_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='token_usage_logs_pkey')
    )
    op.create_index('ix_token_usage_logs_user_id', 'token_usage_logs', ['user_id'], unique=False)
    op.create_index('ix_token_usage_logs_occurred_at', 'token_usage_logs', ['occurred_at'], unique=False)
    op.create_index('ix_token_usage_logs_id', 'token_usage_logs', ['id'], unique=False)
    op.drop_index(op.f('ix_token_usage_user_id'), table_name='token_usage')
    op.drop_index(op.f('ix_token_usage_model'), table_name='token_usage')
    op.drop_index(op.f('ix_token_usage_id'), table_name='token_usage')
    op.drop_index(op.f('ix_token_usage_email'), table_name='token_usage')
    op.drop_table('token_usage')
    # ### end Alembic commands ###
