"""add_token_fields

Revision ID: ad4629cd62fe
Revises: 3cef00bad943
Create Date: 2026-05-07 00:36:50.352487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad4629cd62fe'
down_revision = '3cef00bad943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plans', sa.Column('monthly_tokens', sa.Integer(), server_default='0', nullable=True))
    op.alter_column('subscription_plans', 'features',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('ix_subscription_plans_id', table_name='subscription_plans')
    op.add_column('users', sa.Column('token_balance', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('total_tokens_consumed', sa.Integer(), server_default='0', nullable=False))
    # Use now() for Postgres default timestamp
    op.add_column('users', sa.Column('last_token_reset', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_token_reset')
    op.drop_column('users', 'total_tokens_consumed')
    op.drop_column('users', 'token_balance')
    op.create_index('ix_subscription_plans_id', 'subscription_plans', ['id'], unique=False)
    op.alter_column('subscription_plans', 'features',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('subscription_plans', 'monthly_tokens')
    # ### end Alembic commands ###
