"""Add mock_interview_questions table

Revision ID: e7c5d2bb98f4
Revises: 80ff406ef6c8
Create Date: 2026-04-04 13:27:52.714883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7c5d2bb98f4'
down_revision = '80ff406ef6c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_interview_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('role_title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('intent', sa.Text(), nullable=True),
    sa.Column('expectations', sa.JSON(), nullable=True),
    sa.Column('sample_answer', sa.Text(), nullable=True),
    sa.Column('star_breakdown', sa.JSON(), nullable=True),
    sa.Column('complexity', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_interview_questions_company_name'), 'mock_interview_questions', ['company_name'], unique=False)
    op.create_index(op.f('ix_mock_interview_questions_id'), 'mock_interview_questions', ['id'], unique=False)
    op.create_index(op.f('ix_mock_interview_questions_is_global'), 'mock_interview_questions', ['is_global'], unique=False)
    op.create_index(op.f('ix_mock_interview_questions_role_title'), 'mock_interview_questions', ['role_title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mock_interview_questions_role_title'), table_name='mock_interview_questions')
    op.drop_index(op.f('ix_mock_interview_questions_is_global'), table_name='mock_interview_questions')
    op.drop_index(op.f('ix_mock_interview_questions_id'), table_name='mock_interview_questions')
    op.drop_index(op.f('ix_mock_interview_questions_company_name'), table_name='mock_interview_questions')
    op.drop_table('mock_interview_questions')
    # ### end Alembic commands ###
