"""add_mock_interview_sessions_and_answers

Revision ID: fc621924edb5
Revises: 589bbd66287d
Create Date: 2026-04-05 01:50:42.508884

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc621924edb5'
down_revision = '589bbd66287d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_interview_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_interview_sessions_id'), 'mock_interview_sessions', ['id'], unique=False)
    op.create_table('mock_interview_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('user_answer', sa.Text(), nullable=False),
    sa.Column('star_score', sa.Integer(), nullable=True),
    sa.Column('star_breakdown', sa.JSON(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['mock_interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_interview_answers_id'), 'mock_interview_answers', ['id'], unique=False)
    op.drop_index('ix_resume_templates_id', table_name='resume_templates')
    op.drop_table('resume_templates')
    op.drop_constraint('applications_email_thread_id_key', 'applications', type_='unique')
    op.create_index(op.f('ix_nudges_id'), 'nudges', ['id'], unique=False)
    op.drop_constraint('profiles_user_id_key', 'profiles', type_='unique')
    op.drop_index('ix_profiles_user_id', table_name='profiles')
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    op.alter_column('resume_versions', 'trigger',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='initial_generate | tailor_more | manual_edit | upload | section_edit',
               existing_nullable=True)
    op.alter_column('resume_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_resume_versions_resume_version', table_name='resume_versions')
    op.create_index(op.f('ix_shared_form_structures_id'), 'shared_form_structures', ['id'], unique=False)
    op.drop_index('ix_shared_selector_performance_fp_ats', table_name='shared_selector_performance')
    op.create_index(op.f('ix_shared_selector_performance_id'), 'shared_selector_performance', ['id'], unique=False)
    op.drop_constraint('sync_status_user_id_key', 'sync_status', type_='unique')
    op.alter_column('tailor_contexts', 'source',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='extension | manual_paste | job_listing',
               existing_nullable=True)
    op.alter_column('tailor_contexts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_tailor_contexts_expires_at', table_name='tailor_contexts')
    op.drop_index('idx_tailor_contexts_user_created', table_name='tailor_contexts')
    op.create_index(op.f('ix_tailor_contexts_user_id'), 'tailor_contexts', ['user_id'], unique=False)
    op.drop_index('idx_ufa_user_fp', table_name='user_field_answers')
    op.create_index(op.f('ix_user_field_answers_id'), 'user_field_answers', ['id'], unique=False)
    op.alter_column('user_resumes', 'resume_url',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('user_resumes', 'sections_order',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('user_resumes', 'design_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('user_resumes', 'keyword_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('ix_user_resumes_job_description_hash', table_name='user_resumes')
    op.drop_column('user_resumes', 'resume_source')
    op.drop_column('user_resumes', 'updated_at')
    op.drop_column('user_resumes', 'resume_data')
    op.drop_column('user_resumes', 'job_description_hash')
    op.drop_index('idx_ush_user_created', table_name='user_submission_history')
    op.drop_index('ix_user_submission_history_user_domain', table_name='user_submission_history')
    op.create_index(op.f('ix_user_submission_history_id'), 'user_submission_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_submission_history_id'), table_name='user_submission_history')
    op.create_index('ix_user_submission_history_user_domain', 'user_submission_history', ['user_id', 'domain'], unique=False)
    op.create_index('idx_ush_user_created', 'user_submission_history', ['user_id', 'submitted_at'], unique=False)
    op.add_column('user_resumes', sa.Column('job_description_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('user_resumes', sa.Column('resume_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user_resumes', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user_resumes', sa.Column('resume_source', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.create_index('ix_user_resumes_job_description_hash', 'user_resumes', ['job_description_hash'], unique=False)
    op.alter_column('user_resumes', 'keyword_details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('user_resumes', 'design_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('user_resumes', 'sections_order',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('user_resumes', 'resume_url',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.drop_index(op.f('ix_user_field_answers_id'), table_name='user_field_answers')
    op.create_index('idx_ufa_user_fp', 'user_field_answers', ['user_id', 'field_fp'], unique=False)
    op.drop_index(op.f('ix_tailor_contexts_user_id'), table_name='tailor_contexts')
    op.create_index('idx_tailor_contexts_user_created', 'tailor_contexts', ['user_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_tailor_contexts_expires_at', 'tailor_contexts', ['expires_at'], unique=False)
    op.alter_column('tailor_contexts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tailor_contexts', 'source',
               existing_type=sa.VARCHAR(length=20),
               comment='extension | manual_paste | job_listing',
               existing_nullable=True)
    op.create_unique_constraint('sync_status_user_id_key', 'sync_status', ['user_id'])
    op.drop_index(op.f('ix_shared_selector_performance_id'), table_name='shared_selector_performance')
    op.create_index('ix_shared_selector_performance_fp_ats', 'shared_selector_performance', ['field_fp', 'ats_platform'], unique=False)
    op.drop_index(op.f('ix_shared_form_structures_id'), table_name='shared_form_structures')
    op.create_index('idx_resume_versions_resume_version', 'resume_versions', ['resume_id', sa.text('version_number DESC')], unique=False)
    op.alter_column('resume_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('resume_versions', 'trigger',
               existing_type=sa.VARCHAR(length=30),
               comment='initial_generate | tailor_more | manual_edit | upload | section_edit',
               existing_nullable=True)
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.create_index('ix_profiles_user_id', 'profiles', ['user_id'], unique=False)
    op.create_unique_constraint('profiles_user_id_key', 'profiles', ['user_id'])
    op.drop_index(op.f('ix_nudges_id'), table_name='nudges')
    op.create_unique_constraint('applications_email_thread_id_key', 'applications', ['email_thread_id'])
    op.create_table('resume_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('latex_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='resume_templates_pkey')
    )
    op.create_index('ix_resume_templates_id', 'resume_templates', ['id'], unique=False)
    op.drop_index(op.f('ix_mock_interview_answers_id'), table_name='mock_interview_answers')
    op.drop_table('mock_interview_answers')
    op.drop_index(op.f('ix_mock_interview_sessions_id'), table_name='mock_interview_sessions')
    op.drop_table('mock_interview_sessions')
    # ### end Alembic commands ###
